services:
  # Web Service for the Node.js Server
  - type: web
    name: audio-sync-server
    env: node
    plan: free
    rootDir: "server"
    buildCommand: "npm install"
    startCommand: "node server.js"
    # To avoid having the client and server on the same port,
    # you can expose a different port for the server.
    # ports:
    #   - port: 3000
    #     name: http
    #     protocol: TCP

  # Web Service for the React Client
  - type: web
    name: audio-sync-client
    env: node
    plan: free
    rootDir: "client"
    buildCommand: "npm install && npm run build"
    # This start command uses a simple static server like 'serve'
    # You'll need to add 'serve' as a dependency in your client's package.json
    startCommand: "npx serve -s dist -l $PORT"