services:
  # Web Service for the Node.js Server
  - type: web
    name: audio-sync-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    # The root directory for the service is the 'server' folder
    rootDir: "server"

  # Static Site for the React Client
  - type: static
    name: audio-sync-client
    plan: free
    # The build command runs from the root and builds the React app
    buildCommand: "cd client && npm install && npm run build"
    # The publish directory is where the built static files are located
    staticPublishPath: "client/dist"